[build]
	base = "app"
	command = "yarn build"
	publish = "build"


[template]
  incoming-hooks = []

[template.environment]
  OPENAI_ORG = "Change me to your OpenAI org token"
  OPENAI_KEY = "Change me to your OpenAI secret key!"
